### PR TITLE
fix class diagram mermaid

### PR DESCRIPTION
**Pull request by DanShai**
class diagram fix

### CODE REVIEW

**Comment by DanShai** [comment]
added screenshot of the fix result here :
https://github.com/DanShai/useMermaid-hook

**Comment by knsv** [comment]
Hi @DanShai !

Sorry for late response to this but it has been a busy sporing for all involved. I would like merge this one but there are conflicts now. Would you consider takeing the pull and update the pr? If so that would be great and my response will be much swifter.

Thanks for you efforts.

**Comment by DanShai** [comment]
Hi @knsv ! 
thanx for the reply ! no problem,  I will look into it later today :)

**Comment by DanShai** [comment]
Hi! 
In the last (3rd) commit,  corrected the linter errors , some semicolons and function parenthesis space stuffs were failing the checks ! now it passes the test :)

**Comment by DanShai** [comment]
Hi!
In the last commit, corrected the linter errors , some semicolons and function parenthesis space stuffs were failing the checks ! now it passes the test and no conflicts :)

**Pull request merged**
