### PR TITLE
Add hex shape for flow charts

### PR DESCRIPTION
**Pull request by mearns**
Working on issue #530.

### CODE REVIEW

**Comment by mearns** [comment]
Probably won't be able to work on this until tomorrow night, but should be able to wrap it up then.

**Comment by Dunning-Kruger** [comment]
Hey, thank you very much for the work you've done so far! Looking forward to seeing it complete and merging it!

As a side note, just in case you were not aware, when you do a pull request (even a draft) and then do commits to it, everyone that's subscribed to the repository (mostly collaborators) gets a notification (email or any other type) per each commit so, if possible, avoid doing so.

If you need to do it for a specific reason, or to make your work easier, that's more than fine! It's not a big deal!

image

**Comment by knsv** [comment]
Nice, docs and all! Let me know when done. Will merge this to develop. Collecting changes for version 9 there. Good to have master ready for critical bug fixes.

**Comment by mearns** [comment]
Eek, sorry about that @Dunning-Kruger, didn't realize it would be so noisy. Is there any way to get coveralls to run for me without pushing commits?

**Comment by Dunning-Kruger** [comment]
@mearns I don't think there's an easy way. I believe or current setup is building in travis then pushing the coverage to coveralls, which means that you would have to set up both in your fork.

**Comment by mearns** [comment]
So a little more clean up to do, but I've added some new simple tests for the flow chart shape rendering functions, which required a light refactor (specifically pulling this out into `flowChartShapes.js`. Wonder if the maintainers have any input on this before I go any further (really just pulling things out of the body of `addToRender` to satisfy the max number of lines in that function as called out by codeclimate).

**Comment by mearns** [comment]
I'm done with initial development on this, it's ready for review.

I implemented the hexagon shaping using double curly braces as the markup, sort of in the spirit of "round" versus "circle", but if you have an alternative you'd prefer, let me know:

```
A --> B{regular diamond}
```
vs. 
```
A --> B{{hexagon}}
```

Here's a screenshot of the new element. It's designed to have the side "triangles" always a similar shape (the angles are always fixed). That means it _will_ still grow horizontally as it grows vertically, but not nearly as aggressively as the diamond. I chose this so that the angles don't become too shallow in tall elements, which would make the hex and a rectangle harder to distinguish.

Screen Shot 2019-10-05 at 1 54 48 PM

For reference, here's the diamond with the same contents:

Screen Shot 2019-10-05 at 1 53 35 PM

I noted above a light refactor of the flowRenderer, to pull the shape-rendering functions out into a separate module. The immediate impetus for this was to make up for a decrease in code coverage that came from decreasing the total number of lines (which itself was triggered by codeclimate complaining about the same code appearing multiple times 🙁). I think the refactor is a positive change overall, but if you have other ideas just let me know =)

**Comment by knsv** [comment]
Good job @mearns ! I appreciated your refactoring, it improved the code! I also like that you added many unit tests.

**Pull request merged**
