### PR TITLE
Use dagre-d3 master branch (for d3v5)

### LINKED ISSUE #990: Upstream Peer Dependency dagre
I was just updating my deps, and noticed this. I thought I would mention it, because it seems that the d3 version is out of date ...

```
warning "mermaid > dagre-d3-renderer@0.5.8" has incorrect peer dependency "d3@^4.13.0".
```

Isn't modern d3 `"d3@^5.12.0"`?

(Yes, I know technically that the line here in this project's package.json is:
```json
    "d3": "^5.7.0",
```
So it will properly install 5.12 and any other minor / patch increase. Just wondering if outreach to the dagre repo is warranted.

### PR DESCRIPTION
**Pull request by pravi**
Also switch back to dagre and graphlib. Fixes #990

### CODE REVIEW

**Comment by knsv** [comment]
Thanks for this PR! Good news with dagre family being maintained again. Will pull this BUT ... would you mind doing this from the develop branch? We are trying to keep the master ready for urgent changes.

**Comment by Dunning-Kruger** [comment]
I have put `develop` branch in line with `master`. I believe your branch is now behind in commits (compared to `develop`), and that's why they show up in the PR... but it should still be good to go!

image

Sorry for the inconvenience!

**Comment by pravi** [comment]
@knsv I rebased my branch against develop. Is there anything else I need to do?

**Comment by knsv** [comment]
@pravi All is good, will look at this now. Thanks!

**Comment by pravi** [comment]
@knsv thanks! Are you planning to release this soon? We'll need a new version to update gitlab.

**Pull request merged**
