### PR TITLE
scope all css rules to .mermaid

### PR DESCRIPTION
**Pull request by icewind1991**
Prevents the css from messing with other styles on the site.

### CODE REVIEW

**Comment by blackst0ne** [comment]
@knsv any chance to get this PR merged? :slightly_smiling_face:

**Comment by blackst0ne** [comment]
@tylerlong do you have an ability to merge PRs? :slightly_smiling_face:

**Comment by sclarson** [comment]
If I'm not mistaken this will resolve: https://github.com/knsv/mermaid/issues/584

**Comment by blackst0ne** [comment]
Anyone with permissions, please, merge this bugfix. :slightly_smiling_face: 

/cc @knsv @tylerlong

**Comment by paullbn** [comment]
Waiting for this merge too :innocent:

**Comment by blackst0ne** [comment]
By the way, `mermaid` adds this style (for `neutral` theme): 
```css
svg {
  color: rgb(46, 46, 46);
  font: normal normal 400 normal 13px / 20.8px Menlo, "DejaVu Sans Mono", "Liberation Mono", Consolas, "Ubuntu Mono", "Courier New", "andale mono", "lucida console", monospace;
}
```
which breaks other SVG elements on pages. 

It seems this PR does not fix that styles. :slightly_smiling_face:

**Comment by DoctorBud** [comment]
I would love to see this fixed. In the meantime, other users of Mermaid that are calling `mermaid.render()` may want to adapt my hack, which does the fixup of the CSS before its insertion into the DOM. It's a hack, and I didn't bother turning it into a single Regex, although I think that is doable:

```javascript
function fixupMermaidSVG(svgCode) {
  svgCode = svgCode.replace(/\n/g, '');
  var beginStyleTag = '<style>';
  var endStyleTag = '</style>';

  var beginStyle = svgCode.indexOf(beginStyleTag);
  var endStyle = svgCode.indexOf(endStyleTag);
  var svgStyle = svgCode.slice(beginStyle + beginStyleTag.length, endStyle).trim();
  var svgStyleLines = svgStyle.split(/}/g);
  --svgStyleLines.length; // Assumes last element is ''
  var svgNewStyleLines = svgStyleLines.map(function(line) {
    var bracePos = line.indexOf('{');
    var selectors = line.slice(0, bracePos);
    var body = line.slice(bracePos);
    var selectorsNew = selectors.replace(/,/g, ',.mermaid ');
    selectorsNew = '.mermaid ' + selectorsNew;
    selectorsNew = selectorsNew.replace(/.mermaid .mermaid/g, '.mermaid');

    var newLine = selectorsNew + body;
    return newLine;
  });
  var svgNewStyle = beginStyleTag + svgNewStyleLines.join('}') + endStyleTag;
  svgCode =   svgCode.slice(0, beginStyle) +
              svgNewStyle +
              svgCode.slice(endStyle + endStyleTag.length);
  return svgCode;
}


function mermaidRender(div, code) {
  div.classList.add('mermaid');
  mermaid.render(
    div.id + '_svg',
    code,
    function (svgCode) {
      var svgCodeNew = fixupMermaidSVG(svgCode);
      div.innerHTML = svgCodeNew;
    },
    div
  );
}
```

**Comment by tylerlong** [comment]
Sorry for the late reply guys. 

I am working on version 8.0 and the CSS part has been completely rewritten.

I will merge this PR manually into the latest code base.

**Comment by tylerlong** [comment]
Applied in commit: https://github.com/knsv/mermaid/commit/be33c41a4023a5054b3ab25945d9806d957881c8

**Comment by blackst0ne** [comment]
@tylerlong 

What about this diff? :slightly_smiling_face: 

```diff
diff --git a/src/mermaidAPI.js b/src/mermaidAPI.js
index 2a45de7..6e85592 100644
--- a/src/mermaidAPI.js
+++ b/src/mermaidAPI.js
@@ -440,7 +440,7 @@ const render = function (id, txt, cb, container) {
   const cs = window.getComputedStyle(svg)
   s.innerHTML = `
   ${themes[config.theme] || defaultTheme}
-svg {
+.mermaid svg {
   color: ${cs.color};
   font: ${cs.font};
 }
```

**Comment by tylerlong** [comment]
@blackst0ne I removed that part because I don't what it is. And the CSS style seems to work fine.

**Comment by tylerlong** [comment]
I made it even better. I scope the css with svg ID, so even there are multiple diagrams in the single page, each of them could have different CSS styles: https://github.com/knsv/mermaid/commit/2ed515091f7d45c29db5071c7b3ae8f272503e62

**Comment by blackst0ne** [comment]
@tylerlong is it possible to get a bumped version in npm, please? :slightly_smiling_face:

**Comment by tylerlong** [comment]
@blackst0ne  Yes. `yarn add mermaid@8.0.0-alpha.3`. But keep in mind it's just an alpha version.

**Pull request closed without merging**
