### PR TITLE
added sphinx extension

### PR DESCRIPTION
**Pull request by mgaitan**

### CODE REVIEW

**Comment by knsv** [comment]
Merged, thx! Cool with sphinx support!

**Comment by mgaitan** [comment]
:+1: you welcome

**Comment by mgaitan** [comment]
@knsv hey, why it is still not shown? 

image

**Comment by knsv** [comment]
Hi!

 

It is there now.

 

I had to regnerate the docs from the markdown files and push them to the gh-pages branch.

 

Thanks for pointing it out.

 

/Knut

 

Från: Martín Gaitán <notifications@github.com>
Svara till: knsv/mermaid <reply@reply.github.com>
Datum: måndag 5 december 2016 14:47
Till: knsv/mermaid <mermaid@noreply.github.com>
Kopia: Knut Sveidqvist <knut@sveido.com>, Mention <mention@noreply.github.com>
Ämne: Re: [knsv/mermaid] added sphinx extension (#371)

 

@knsv hey, why it is still not shown?

**Comment by thjensuit** [comment]
Hi @mgaitan 

May you have me in case that was not generated the flowchart at the following issue:https://github.com/knsv/mermaid/issues/507

Thank you.

**Pull request merged**
