### PR TITLE
add axisFormat option to ganttConfig

### PR DESCRIPTION
**Pull request by rk0dama**
enable to change the axisFormat with just entering the string format

### CODE REVIEW

**Comment by rk0dama** [comment]
this is related to #269

**Comment by tylerlong** [comment]
This is Awesome!

However, I am working on version 8.0. And version 8.0 works with D3 V4 instead of D3 V3.

And D3 V4 has different syntax to apply axis format.

I will apply this PR manually then.

Thank you very much for this great PR.

**Comment by tylerlong** [comment]
Partially done: https://github.com/knsv/mermaid/commit/37076d3d1f76f289f1ee1ab760d587c363d741a1

**Comment by tylerlong** [comment]
I have done the manual migration of this PR: https://github.com/knsv/mermaid/commit/f62736c7496cccb486b93a155da038baeba700e8

Thank you very much!

**Pull request closed without merging**
